name: Integration Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  prepare-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-versions.outputs.versions }}
    steps:
      - name: Create version list
        id: set-versions
        run: |
          VERSIONS="${{ vars.SPLUNK_VERSIONS }}"
          
          # Convert comma-separated to JSON array
          JSON_ARRAY=$(echo "$VERSIONS" | jq -R -c 'split(",") | map(gsub("^\\s+|\\s+$";""))')
          echo "versions=$JSON_ARRAY" >> $GITHUB_OUTPUT
          echo "Testing Splunk versions: $JSON_ARRAY"

  integration-test:
    needs: prepare-versions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        splunk_version: ${{ fromJson(needs.prepare-versions.outputs.versions) }}
    
    name: Integration Test (Splunk ${{ matrix.splunk_version }})
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install UCC Framework
        run: pip install splunk-add-on-ucc-framework
      
      - name: Build add-on
        run: ucc-gen build --source alert_apprise/package --ta-version 0.0.1-test
      
      - name: Prepare test environment
        run: |
          cd alert_apprise/tests/integration
          
          mkdir -p nginx/webhook_logs
          chmod 777 nginx/webhook_logs
      
      - name: Start Docker services
        env:
          SPLUNK_VERSION: ${{ matrix.splunk_version }}
        run: |
          cd alert_apprise/tests/integration
          docker compose up -d
          
      - name: Verify webhook delivery
        run: |
          cd alert_apprise/tests/integration
          ./verify.sh 180
      
      - name: Cleanup
        if: always()
        run: |
          cd alert_apprise/tests/integration
          docker compose down -v
          
          # Clean up log files
          rm -rf nginx/webhook_logs/*.log
